# Generated by Django 4.2.4 on 2023-08-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.hero')),
            ],
        ),
    ]
