# Generated by Django 4.2.4 on 2023-08-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='hero',
        ),
        migrations.AddField(
            model_name='hero',
            name='aboutme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='portfolio.skill'),
        ),
    ]
