# Generated by Django 4.2.4 on 2023-08-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_aboutme_hero_remove_skill_hero_hero_aboutme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.hero'),
        ),
        migrations.AddField(
            model_name='skill',
            name='hero',
            field=models.ManyToManyField(to='portfolio.hero'),
        ),
    ]
