# Generated by Django 4.2.4 on 2023-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_hero_aboutme_remove_hero_skills_aboutme_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hero', models.ManyToManyField(to='portfolio.hero')),
            ],
        ),
    ]
