# Generated by Django 4.2.4 on 2023-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email',
            field=models.EmailField(default='samirshrs27@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hero',
            name='location',
            field=models.CharField(default='Budhanilkantha, Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='phone',
            field=models.CharField(default='9826851038', max_length=50),
        ),
    ]
